### ISSUE TITLE
Morning session M2 D2

### ISSUE THREAD

**Issue by LionRouge1** [L2oukmane/To-Do-List#5]
Hi @L2oukmane  :wave: 
Great job on implementing this awesome project with all the colors
The project looks really good and everything is working normally.

- To be honest, we didn't find any issue with your project. Everything is okay.

- The code is highly clean and organized.

- Features are working properly.

GOOD JOB once again and happy coding :smile:

**Comment by misheck12** [comment]
Hey @L2oukmane Great Work this project looks awesome and am hear to confirm your clean code writing skill
